# Generated by Django 2.2.1 on 2019-06-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190624_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aventura',
            name='deslikes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='aventura',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
